### ISSUE TITLE
 A plugin tried to deny a command with signable component(s). This is not supported. Disconnecting player <nickname>

### ISSUE THREAD

**Issue by RealKomander** [PaperMC/Velocity#1007]
Only a few players experience this issue, especially ones playing on TLauncher or versions 1.19.3+ (2 completely random factors, I know).

75% of the times they try joining, this message appears to them:
![image](https://user-images.githubusercontent.com/124439290/236015280-daba9abc-5254-4691-93ad-6b044557d395.png)

And this error is prompted in the console:
`[21:46:39 FATAL]: A plugin tried to deny a command with signable component(s). This is not supported. Disconnecting player deishoke`

Full logs are attached, sorry if it's not a velocity error, but it still happens without plugins.

[latest.log](https://github.com/PaperMC/Velocity/files/11389960/latest.log)

**Comment by RealKomander** [comment]
I still don't understand how it blames a plugin, but this issue still happens without them. Unfortunately, I don't have time to test it right now, I'll send logs without plugins in the near future if you want them for some reason

**Comment by electronicboy** [comment]
If this is happening without plugins, we'd need a log showing that, and
info of the command being executed

The only way message shows is if a command packet is denied by something in
the proxy when there is a signed component in the command

**Comment by mi2sha** [comment]
это все из-за пупу каки

**Comment by Nacioszeczek** [comment]
I'll be closing this as stale. If the issue still occurs please reply with the requested logs and it'll be reopened.

**Comment by A248** [comment]
This is not stale. It is a real issue that is hard to track down, and it has affected multiple users.

Over the course of 2 years or so, 6 users have reported this problem to me.

This is not a matter of plugins or no plugins. A plugin that merely registers a command shouldn't cause players to be disconnected.

**A potential lead**
I received the first report of this bug in July 2024. A user was having trouble on Velocity build `#402`.

They performed their own debugging, and as soon as they downgraded to build `#400`, the problems stopped.

The user concluded that code changes surrounding commands with signable component caused this error. Due to a lack of communication neither of us filed a bug report, but this bug surfaced rarely and has been a shadowy menace since. It seems to be the product of nondeterministic factors as I can never reproduce it, but it comes back repeatedly to haunt users of my plugin (LibertyBans) which registers the /ban command.

**Logs**
Today I obtained logs from a user experiencing this bug.

[2026-04-11-6.log](https://github.com/user-attachments/files/26649046/2026-04-11-6.log)

**Comment by electronicboy** [comment]
We can't process cancelling signed chat messages and such on the proxy without entering illegal state territory in which your user would be disconnected the next time they send a signed chat/message to the server; This is generally not considered a bug and is sadly a limitation of the MC protocol, the only way to get around this right now would be using a plugin like signed velocity, otherwise, we would need some means of handshaking with the server to be able to aknowledge what has happened 

Our stance is that between "kick the player", "let them do it anyways" and, "enter illegal non-recoverable state which causes questionable state", kicking felt like the least evil, especially when the client was a lot more active towards just booting people in said state

**Comment by A248** [comment]
Oh, I understand that. My question is though, why isn't it reproducible?

I suspect something more complicated is going on here. This is the error message; please take a look, as these are not signed chat messages we're talking about. I can't reproduce it, but other users have -- even with no other plugins installed.

```
[22:55:15 INFO]: [server connection] Blue_Gamer48 -> lobby has connected
[22:55:31 FATAL]: A plugin tried to deny a command with signable component(s). This is not supported. Disconnecting player Blue_Gamer48. Command packet: SessionPlayerCommand{command='ban Blue_Gamer48 Test', timeStamp=2026-04-11T20:55:31.326Z, salt=-1618365530119402377, argumentSignatures=ArgumentSignatures{entries=[ArgumentSignature{name='reason'}]}, lastSeenMessages=LastSeenMessages{offset=0, acknowledged={}, checksum=1}}
[22:55:31 INFO]: [connected player] Blue_Gamer48 (/188.108.208.192:60113) has disconnected: A proxy plugin caused an illegal protocol state. Contact your network administrator.
[22:55:31 INFO]: [server connection] Blue_Gamer48 -> lobby has disconnected:
```

Two important notes:
1. The command has signable components in the error message. However, my plugin doesn't use signable components. This may be a bug caused by overlap with vanilla /ban.
2. No plugin is canceling any event. All that happened is a Velocity plugin registered a command, and this causes spurious failure. Still today, I do not have a good lead on what are the conditions that trigger this error.

**Comment by WouterGritter** [comment]
Is this log coming from `SessionCommandHandler` or `KeyedCommandHandler`? Unfortunately both classes share the `logger` instance of their interface, `CommandHandler`, which is not ideal. Would probably good to fix this, also.

**Comment by A248** [comment]
SessionCommandHandler. You can tell because `SessionPlayerCommand{...}` is the toString() output for the packet.

I just checked the code, and there are 5 code paths generating a similar message. Although it doesn't affect this issue, I submitted a PR to clarify the 2 of 5 that were ambiguous: #1773

**Comment by A248** [comment]
Can this issue be re-opened? I have provided significant documentation and leads.

This is **not** about signed chat messages, but rather simple registration of *unsigned* commands.
