### ISSUE TITLE
Support for dependency handling from mavencentral

### ISSUE THREAD

**Issue by Coder-Iro** [PaperMC/Velocity#1008]
Currently, velocity does not have the ability to handle dependencies in mavencentral. https://docs.papermc.io/velocity/dev/dependency-management#external-dependencies
However, in the case of Waterfall or Paper, it automatically downloads and adds classpath for dependencies uploaded to maventral. https://docs.papermc.io/paper/dev/plugin-yml#libraries
I open this issue because I think it would be very convenient for developers if this function was also in Velocity.

**Comment by electronicboy** [comment]
See, this was generally a “no” in the past as pretty much all currently implementations of this actually violate the TOS, so there’s very little chance that this will be added of by us

**Comment by astei** [comment]
Closing as "not planned".

The only reason why this feature exists in Paper and Waterfall is because upstream Spigot and BungeeCord have it. The features in both as currently designed violate the Maven Central terms of service.

Library dependency management is a pretty hard problem to solve and inevitably involves compromises.
