### ISSUE TITLE
Restricted server access

### ISSUE THREAD

**Issue by tomkeuper** [PaperMC/Velocity#1035]
Just like the old bungee had `restricted: true` it would be good to have an implemented method to block server access instead of relying on a plugin.
I currently found 2 plugins that technically could do the job in a way but they both seem to only block the server command usage.  Such a plugin makes every server restricted instead of also being able to use a blacklist only approach.
In my opinion it would be better to have something related to security build in to prevent possible problems in the future.

**Comment by electronicboy** [comment]
Blocking server command usage was exactly how it works in bungee, the
entire option in bungee exists solely for the server command, nothing more,
nothing less

It's never been used outside of that, and imho, it makes little sense for
us to adopt it, especially when it could be handled via a 10 minute plugin
which has the restrictions you want, offering much more control than is
really tenable for a built in solution

A core tenant of velocities principles is that we don't flood the proxy
with half baked features, but serve to offer the tools so that plugins do
this sorta stuff, otherwise you just end up with a state where the built in
feature suck and either up up having to effectively maintain the proxy, a
server switching command plugin with 20 features, a perm plugin, etc, etc
