### ISSUE TITLE
InnetAddress#getHostname() can't authenticate premium players on PreLoginEvent

### ISSUE THREAD

**Issue by Yboy06** [PaperMC/Velocity#1049]
**ISSUE:** I was trying to log `event.getConnection().getRemoteAddress().getHostName()` on **PreLoginEvent**, when I realised premium/online-mode users were not authenticating with Minecraft.net. After some tests, I realized the issue comes when calling InnetAddress#getHostname()

**SOLUTION GIVEN BY `electroniccat` IN DISCORD:** He told me to disable the "prevent-proxy-connections" options, and well, that worked, but I'm sure it's not a good idea to disable that in order to make hostnames work.

Can anyone find what is happening here and solve it without disabling "prevent-proxy-connections" option?

Thanks in advance!

**Comment by Nacioszeczek** [comment]
Please specify what the issue in Velocity is.
[`PreLoginEvent`](https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/connection/PreLoginEvent.html) is fired before any Mojang authentication, so obviously the player will not be authenticated at that point.
[`InetAddress#getHostName()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/InetAddress.html#getHostName()) is a method from the JDK, not Velocity, so that isn't something we can fix either.

**Comment by electronicboy** [comment]
we'd need to clone the address for the event

**Comment by Yboy06** [comment]
> Please specify what the issue in Velocity is. [`PreLoginEvent`](https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/connection/PreLoginEvent.html) is fired before any Mojang authentication, so obviously the player will not be authenticated at that point. [`InetAddress#getHostName()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/InetAddress.html#getHostName()) is a method from the JDK, not Velocity, so that isn't something we can fix either.

For example, doing this always ends up kicking players because they cannot be authenticated with Minecraft.net
```java   
    @Subscribe
    public void onPrelogin(final PreLoginEvent e) {
        logger.info("HOST NAME: "+e.getConnection().getRemoteAddress().getHostName())
    }

**Comment by Xernium** [comment]
# All of this is intended behavior
And I‘ll gladly clear up the misunderstanding here.
## What‘s happening:
Using this method [`InetAddress#getHostName()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/InetAddress.html#getHostName()) causes the system to look up the reverse DNS name for the socket address. After this request the object is then a resolved address.
### The issue
The (text) socket address is appended in the authentication request. **If this is a resolved address it will be the hostname instead of the address**. That‘s an issue because the authentication server (most likely) expects the unresolved address, which, will no longer be correctly identifiable at this point.
### Solution
Use [`InetSocketAddress#getHostString()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/InetSocketAddress.html) instead, this doesn‘t cause a lookup. For now this can be safely casted, but this may not be the case in the future. Use `toString()` as viable fallback

### Why we won‘t fix this on our side:
A couple of plugins already use this to rewrite the used remote address (namely plugins like TCPShield) and we don‘t plan on breaking this, at least not for now.
**Note**: We should clarify the javadoc around this area more

**Comment by electronicboy** [comment]
There is a part of me that generally thinks that the behavior around this can and should be improved, should we just store the passed in IP as raw string and discard it if people replace it? Not 100% sure on the ideal here, but this feels like such a weird trap

**Comment by Xernium** [comment]
> There is a part of me that generally thinks that the behavior around this can and should be improved, should we just store the passed in hostname as raw string and discard it if people replace it? Not 100% sure on the ideal here, but this feels like such a weird trap

Agreed on the weird trap part. The other part is best practice. Sadly the address objects don’t have an immutable form (yet) so we cant wholly avoid these issues sometimes.

I‘d also be for labeling all mutable fields or field references in the API just to nail home that point. Maybe.
