### ISSUE TITLE
Player#sendPluginMessage doesn't sending data.

### ISSUE THREAD

**Issue by Straikerinos** [PaperMC/Velocity#1068]
After build 264 (tested also with build 265) sending PluginMessage via specified player isn't no longer working.
I have to use directly ServerConnection to send Plugin message.
Code:
`
ByteArrayDataOutput out = ByteStreams.newDataOutput();
out.writeUTF("info-test");
source.sendPluginMessage(MinecraftChannelIdentifier.from("gk:test"), out.toByteArray());
`
Bukkit (paper) side: git-Paper-159 (MC: 1.20.1)

**Comment by electronicboy** [comment]
what do you mean, "via specified player", cos sending a plugin message to the player will send the message to the player and not to the server

**Comment by kyngs** [comment]
Is this related to #591? Cuz that is build 264

**Comment by Straikerinos** [comment]
> what do you mean, "via specified player", cos sending a plugin message to the player will send the message to the player and not to the server

In older builds it was possible to send a PluginMessage directly like this.
But now in this case nothing is sent and no PluginMessage is sent to the server where the player is.

**Comment by electronicboy** [comment]
Player#sendPluginMessage has always sent the plugin message to the client, nothing has changed on that front, unless you mean you're calling that inside of bukkit and the proxy isn't sending data back when you do that; In which case, all I can guess is going to boil down to making sure that you properly registered your channels and are using the latest build, otherwise, we'd need more repo info

**Comment by Straikerinos** [comment]
If it never worked from Proxy -> Bukkit side, then it's my fault.
