### ISSUE TITLE
[VELOCITY REQUEST] Integrate a Load Balancer into Velocity

### ISSUE THREAD

**Issue by TMKCRepo** [PaperMC/Velocity#1129]
https://www.spigotmc.org/resources/playerbalancer.55011/

This plugin is SUPER GOOD for Velocity if you are running something like Folia or MultiPaper.

Maybe integrate something like it into Velocity so that Velocity has its own Load Balancer and so you can tune the configs for better scaling?

Right now it is a pain to get everything to work with a separate Load Balancer plugin, so having some form of a Load Balancer built-in would be super good and super useful since scalable Minecraft servers are getting more and more popular.

**Comment by 4drian3d** [comment]
Plugins exist to integrate this type of mechanics according to what each user requires, not everyone requires this type of mechanics in the same Velocity, there are even more than 1k proxies that do not have plugins installed in Velocity (according to bstats) that definitely do not require this mechanics

**Comment by electronicboy** [comment]
It's a general goal for velocity to keep the proxy as light as possible, because otherwise you end up with what is effectivly either a minimal effort product which fits only a small % of needs, or you end up maintaining effectively two full projects inside of one project, which generally does nobody any good, be that project maintainers or users, etc.

The entire point is for us to maintain an API for plugins to be able to offload that functionality, if there is missing API, we are more than welcome to look into that, but, I fail to see what advantages trying to merge such a featureset into the proxy itself would do which isn't already fulfulled.
