### ISSUE TITLE
Can't cancel message.

### ISSUE THREAD

**Issue by KamlaXPL** [PaperMC/Velocity#1226]
[12:50:58 INFO]: [server connection] Klotix32 -> lobby01 has connected
[12:51:01 FATAL]: A plugin tried to cancel a signed chat message. This is no longer possible in 1.19.1 and newer. Disconnecting player Klotix32

It is impossible to cancel messages or commands from Velocity, although on bungeecord it works.

**Comment by electronicboy** [comment]
Not a bug, this is intentional behavior otherwise we corrupt the chain. your only options are basically to strip the signature entirely using a plugin, or use signedvelocity.

bungee will let you cancel stuff, but will corrupt the chain and cause various sets of issues there, we cannot know if you've disabled that stuff on the backend server in some manner, and thus prefer to just prevent it from occuring until we have proper support for it.
