### ISSUE TITLE
Velocity doesnt work with Forge 1.12.2 (even with spongeforge)

### ISSUE THREAD

**Issue by Biraru** [PaperMC/Velocity#1417]
### Expected Behavior

Connects to the server without any errors with mods from forge

### Actual Behavior

so i made a velocity server and a modded forge server with one mod as a test. (no sponge rn)
configured everything (velocity and forge) but when i tried connecting it looked like velocity didnt forward the mod list from the player to the server. so the server replied with "this server requires mods smth smth forge/fml"
after that i added sponge and configured it (bungeecord.ip-forward, etc) following the wiki of spongepowered. it still didnt work and showed the same error. it seems like velocity didnt forward the mod list from the client

### Steps to Reproduce

configure velocity and forge, connect with forge to the server with both having the same mod (atleast one mod is required or the forge client just sends a vanilla handshake)

### Plugin List

none

### Velocity Version

[22:00:14] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Booting up Velocity 3.3.0-SNAPSHOT (git-956fca14-b421)

**Comment by Biraru** [comment]
forgot to mention, waterfall works with forge but am trying to use velocity

**Comment by Powerspieler** [comment]
Got the same issue with "Disconnecting Player: This server has mods that require FML/Forge to be installed on the client", tho i have all the mods installed. My Config:

velocity.toml:
player-info-forwarding-mode = "legacy"

Forge 1.12.2 Server with SpongeForge Mod:
./config/sponge/global.conf:
sponge.bungeecord.ipforwarding=true
sponge.modules.bungeecord=true

Edit: its 4 AM in the morning and i forgot to set online-mode=false in the server.properties. Its working now. maybe this is your problem too, because the behavior you're describing was actually like mine

**Comment by Biraru** [comment]
yea i already got this problem fixed, i didnt have sponge.modules.bungeecord on
