### ISSUE TITLE
PluginMessageEvent is not called for BungeeCord plugin messages

### ISSUE THREAD

**Issue by galacticwarrior9** [PaperMC/Velocity#438]
I've been trying to update a very small Velocity plugin for my server which listens to BungeeCord plugin messages using PluginMessageEvent. However, it seems the event is not called for these.

In a [conversation](https://discord.com/channels/472484458856185878/472804531751747585/797819671746838529) that took place in the Velocity Discord on January 10, it was stated that this stopped being called after 1.1.x. It was also stated that this was an "oversight" and [this](https://github.com/VelocityPowered/Velocity/blob/dev/1.1.0/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/BungeeCordMessageResponder.java#L352) should return false. Because of that comment, I have opened this as an issue; I apologize if that is not actually the case.

**Comment by hugmanrique** [comment]
Your plugin should not depend on messages sent via the BungeeCord channel. Register your own channel identifier and send all required information with that identifier.

**Comment by astei** [comment]
Velocity does not promise to be bug-for-bug compatible with BungeeCord. If for some reason you need to handle the BungeeCord channel specially, you can disable [this setting in your velocity.toml](https://github.com/VelocityPowered/Velocity/blob/dev/1.1.0/proxy/src/main/resources/default-velocity.toml#L115). Note that then you are responsible for reimplementing all the functionality Velocity would have otherwise provided for you.

**Comment by astei** [comment]
Note that if you're referring to BungeeQuack, its functionality has been long integrated into Velocity itself. I've linked the setting to disable it.
