### ISSUE TITLE
Reduce Spamming

### ISSUE THREAD

**Issue by NonSwag** [PaperMC/Velocity#484]
Hey there,

My Velocity logs are very big due to the connection information
(player (dis)connected and connection timed out messages)
I already tried to automatically delete old logs, but sometimes I need them, so this is not a good solution
It would be great to have an option to disable the logging of those messages
like a setting: "print-connection-information=false"

**Comment by KoxSosen** [comment]
I agree. I mean it's no that hard to setup a cron job to nuke those logs for you, but where the issue could really happen is the latest.log. 
I had cases where I was testing a dev version of a plugin, and got a log of 500mb under 1-2 minutes because an error that didn't had a fix until a few hours. Please also add an option with this something like `print-errors=false`.

**Comment by hugmanrique** [comment]
You can already configure the logger's level and filters creating a [Log4j config](https://logging.apache.org/log4j/2.x/manual/configuration.html). See https://github.com/VelocityPowered/Velocity/blob/dev/1.1.0/proxy/src/main/resources/log4j2.xml for Velocity's default configuration (as of 1.1.0, might change in the future).
