### ISSUE TITLE
TabcompleteEvent is only fired for non commands

### ISSUE THREAD

**Issue by Nononitas** [PaperMC/Velocity#532]
Hello,

the TabcompleteEvent is only fired for non commands like " [tab]".
It will not fired for example:
 - "/help [tab]"
 - "/he[tab]"
 - "server [tab]"

I don't think that's supposed to be the case

Velocity: Velocity 1.1.9-SNAPSHOT (git-baaf91a0-b444)
Server version: 1.12

**Comment by astei** [comment]
This is (for now) intentional, and it has everything to do with the fact that Minecraft 1.13 and higher have a totally different tab complete system, which can be controlled by an event as well. I've been tied up in the question of how to expose this neatly in the idea and have yet to come up with something.

It's probably too disruptive of a change for Velocity 3.0.0 at this point. Maybe Polymer would fit, but that's a ways out.
