### ISSUE TITLE
[issue] error in console

### ISSUE THREAD

**Issue by WarnDa** [PaperMC/Velocity#554]
Hello,

I'm using velocity 3.0.1-SNAPSHOT with a backend server on 1.12.2.

And when a player connected I saw this error : 
https://pastebin.com/wGAzEDKR

**Comment by ghost** [comment]
Seems to be an error connecting with 1.9.3. Are you able to reproduce this yourself?

**Comment by WarnDa** [comment]
I tried myself (1.9.3) no problem, but on disconnect I had an error in the console 

`>.... [21:03:13 INFO]: [connected player] WarnD has connected
>.... [21:03:13 INFO]: [server connection] WarnD -> SkyZ has connected
>.... [21:03:18 INFO]: [connected player] WarnD  has disconnected: Une erreur interne sest produite lors de votre connexion.
>.... [21:03:18 ERROR]: [connected player] WarnD : exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@2bf75c9e
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
>.... [21:03:18 INFO]: [server connection] WarnD -> SkyZ has disconnected`

**Comment by astei** [comment]
There appears to be insufficient detail to have anything actionable. The `Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.PluginMessage in SERVERBOUND protocol 1.9.3` error looks bad, but without further information like plugins installed on the proxy, all that's left is to examine the behavior, and there is definitely an ID assigned for that particular packet and protocol version, so that basically means a plugin messed up.

The second error is an unclean disconnect from the client side and there is nothing we can do about that.
