### ISSUE TITLE
Denial of Service using Mojang isJoined

### ISSUE THREAD

**Issue by steve-hb** [PaperMC/Velocity#568]
Hey,

in case someone tries to connect to Velocity using multiple IPs and "fake" usernames, one could easily start a Denial of Service by opening connections, force Velocity to check the username with Mojang and do some crypto stuff (e.g. decrypting rsa) before even sending the request to Mojang.
While Velocity waits for Mojang to respond with "I don't know this guy" (remember: the username doesn't exist at all), the client can easily close the connection and start new ones.

This behavior could lead to DoS and should be prevented by either throttling all connection - which could affect other users aswell - or by blocking the user's IP. Blocking IPs isn't a great move - since ISPs are tunneling multiple v6 only households through a single IPv4 address, which could cause innocent users to be blocked/banned.
We thought about other methods (like only throttling the "unlegit" IPs), but the only way to effectively stop these attacks, seems to just block some IPs from starting new login requests.

The mentioned code:
https://github.com/VelocityPowered/Velocity/blob/ec4d2d45a1b367e1607b1a9ff1ba874ab8501a20/proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java#L157

//Oh btw: We also see the possibility that the attackers could use legit usernames

**Comment by astei** [comment]
Closing as a WONTFIX.

When receiving `EncryptionResponse`, the shared secret that is negotiated by the client and server is encrypted in the packet using RSA (specifically with PKCS#1 v1.5 padding... you can already tell security was not very high on the list of priorities for Mojang). So we have no choice but to do an RSA decryption whether we want to or not - there is no other choice. Otherwise, the request to Mojang's authentication servers would rightfully fail.

It is our policy to resist denial of service attacks where we can and where it is practical. Unfortunately, the only practical mitigation on our end is a global rate limit on login attempts, which would protect the server at the cost of frustrating legitimate users. Therefore the only good solution is to use a Minecraft-specific protection solution, such as TCPShield or Cosmic Guard.

The real solution that only Mojang can implement is to either replace the cryptographic primitives in the protocol or get rid of encryption in the protocol entirely. The encryption scheme used in them Minecraft protocol is insecure anyway because it uses the shared secret as the IV and the key to AES-CFB8, and the encryption of the shared secret and verification secret is done using RSA with a known insecure padding scheme.
