### ISSUE TITLE
Question about forwarding different minecraft version

### ISSUE THREAD

**Issue by RuofengX** [PaperMC/Velocity#575]
This is a feature request.
I have 2 servers needed to reverse-proxy, and they using different protocol, let's say the one is 1.12.2Forge and the other is 1.16.5bukkit.
I want to use one IP, one port and 2 domains to establish a proxy.(To save data usage and use port 25565)

---

Solution one is add the feature that forward these 2 different data streams to different ports, like sni solution in nginx(I don't know weather nginx could solve my problem)
Solution two is add the feature that velocity could natively distinguish more than one protocols and sent them to different upstream.

**Comment by astei** [comment]
The first request can be satisfied with the use of the forced hosts feature. The second request is satisfied by default since Velocity supports Forge on Minecraft 1.12.2 and Bukkit-based Minecraft 1.16.x servers.

**Comment by RuofengX** [comment]
Yes, that's true. But what if I want to set different 'player-info-forwarding-mode' for each server? I want my bukkit(actually paper1.16) and forge1.12 both have the IP forward feature. And according to this page [https://velocitypowered.com/wiki/users/forwarding/](https://velocitypowered.com/wiki/users/forwarding/), It seems like I can only choose only one IP forwarding. Any config tips?

**Comment by astei** [comment]
#304 tracks that issue

**Comment by Hallo5000** [comment]
I just finished working on a different approach: (possible on a single domain)
This plugin will check through a list of servers on Join and compares their protocol versions (game versions) to the clients 
[VelocityVersionBouncer](https://github.com/Hallo5000/VelocityVersionBouncer) 
...also I know this issue is 4 years old xD but for anyone searching for a solution like I did this will hopefully help you
