### ISSUE TITLE
It seems like protocol support doesnt like velocity modern forwarding.

### ISSUE THREAD

**Issue by jokbon** [PaperMC/Velocity#616]
Protocol support breaks forwarding completely. "your server did not sent forwarding request to velocity"  I think this is important cause via version only supports 2 versions and now most of velocity users have to switch to bungeeguard.

[](https://github.com/ProtocolSupport/ProtocolSupport/issues/1240)

_Shevchik commented on 15 Sep 2020_
_Modern forwarding doesn't work for < 1.13 so i guess this won't be a thing until ProtocolSupportVelocity becomes a thing (So i can transfer data at login state for old versions)._

**Comment by jokbon** [comment]
https://github.com/ProtocolSupport/ProtocolSupport/issues/1240

**Comment by Xernium** [comment]
I don’t see an issue here. Velocity is working as intended. Modern forwarding is supposed to work with versions 1.13 and above because earlier versions don’t have the protocol features necessary to make it work. 
Though I have to say this; If ProtocolSupport intends to change it as a plugin it needs to make sure the proxy thinks the version the player is on matches or is above 1.13 because there is a hard-coded barrier for that in the proxy code.
