### ISSUE TITLE
Null previous server in connection events on kick redirect

### ISSUE THREAD

**Issue by roccodev** [PaperMC/Velocity#633]
When you're kicked from a server and the kick event results in a redirect action, both `ServerConnectedEvent` and `ServerPostConnectEvent` will have empty/null previous servers.

I'm not sure whether this is the intended behaviour, as the documentation only specifies it being null when they weren't connected to a server beforehand. If it is, it'd be nice to have another way to get whether the player has just joined the proxy instead of just switching servers.

**Comment by AoElite** [comment]
This issue is also present for the player's current server on the `DisconnectEvent` whenever they are kicked from a server.

**Comment by kyngs** [comment]
In TransitionSessionHandler#handle(JoinGame) we use Player#getConnectedServer to get the previous connection and then get the server from it. We then pass the server to the event.

https://github.com/PaperMC/Velocity/blob/5ee96606f6ad55a80f46a4d6b927c9bedf6d7039/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/TransitionSessionHandler.java#L91

https://github.com/PaperMC/Velocity/blob/5ee96606f6ad55a80f46a4d6b927c9bedf6d7039/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/TransitionSessionHandler.java#L107-L108

However, in ConnectedPlayer#handleKickEvent we clear the connection way before the ServerConnectedEvent gets fired.

https://github.com/PaperMC/Velocity/blob/5ee96606f6ad55a80f46a4d6b927c9bedf6d7039/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java#L654-L658

While we keep the information whether the player has been connected anywhere before, it is only a boolean and it is used only if the result was Notify. 

https://github.com/PaperMC/Velocity/blob/5ee96606f6ad55a80f46a4d6b927c9bedf6d7039/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java#L711-L717

I'm not 100% sure whether this is intentional or not, but I think it is the cause for this issue.
