### ISSUE TITLE
[Bug] Bypass permissions in high ping environments

### ISSUE THREAD

**Issue by Cursor-S** [PaperMC/Velocity#693]
Now I have two servers, one is in survival mode and I have **no permission** to execute `/tp` command, the other is in creative mode that I can use `/tp`.

My ping is about 3000ms and I executed `/tp ~ 256 ~` and `/server survival` in the creative server.

I noticed that firstly I was teleported into the sky in creative, then I was switched to the survival server and was teleported into y256 too and I fell and dead.

I don't know what exactly happened, according to the logs, seems that i just executed the command in creative, but actually it did effect to me in survival mode.

**Comment by Xernium** [comment]
Velocity is not capable of facilitating things like this. My best guess is the change position packet only reached you after the server switch. This is not a Velocity bug and due to how the software is designed it can‘t be. In any case you had a desynced client and there’s nothing we can do about that.
