### ISSUE TITLE
Tablist not initialized when moving servers

### ISSUE THREAD

**Issue by Pantera07** [PaperMC/Velocity#706]
Tablist not initialized when moving servers
https://youtu.be/sVJ1yoYMkkg

test1 does not have the tablist plugin, and test 2 has the tablist plugin.

tablist plugin: https://www.spigotmc.org/resources/animated-tab-tablist.46229/

**Comment by montlikadani** [comment]
This is not Velocity issue.

**Comment by Xernium** [comment]
@montlikadani thats not entirely correct, but it’s not going to be a trivial fix. I’ll see what I can do.

**Comment by montlikadani** [comment]
This is my tablist resource, he's probably using the bukkit version of TL or bungee. The TL bungee version includes functionality that can display tablists on several different servers. If not set to one, it will not display the configured tablist, only the default.

On the other hand, if he uses only the TL version of bukkit and it is only installed on ServerA but not on ServerB, the tablist will not appear on ServerB.

I can't really believe this would be a Velocity problem.

**Comment by Xernium** [comment]
But the list appears on the server that doesn’t have it installed. Or rather the header/footer does because it’s not cleared. The plugin is only on one server and not on the proxy itself so it’s technically a proxy issue. Fix is to queue tablist messages during switch, clear the list on the client, and then forward what the new server has already sent.

**Comment by montlikadani** [comment]
Oh, I was confused with such a basic problem "why doesn't it show up" but looking at the video better, I now know what the problem is, sorry.
