### ISSUE TITLE
1.6.4 support

### ISSUE THREAD

**Issue by Cakeprogress** [PaperMC/Velocity#719]
Good afternoon, could you add support for 1.6.4?

**Comment by Astralchroma** [comment]
Older versions are generally unsupported so your answer will probably be "no".

**Comment by Xernium** [comment]
Supporting versions prior to 1.7(.2) would require velocity to have a full packet rewriter and an implementation of every possible game packet. That’s due to how the protocol worked prior to the network protocol rewrite (non-framed-packets).
That’s not only difficult to get working but it also requires a large unwarranted rewrite which we will not consider for a legacy feature.
