### ISSUE TITLE
Add some packets similar to plugin message channel API

### ISSUE THREAD

**Issue by Sanluli36li** [PaperMC/Velocity#741]
At present, the API can only know the communication content between the client and the server through the plugin channel. I can't tell what to do by listening for packets. It is also difficult to send packets directly to the player
a few examples:
1. When a player switches to another server, I need to add it to the previous server player's tablist, but I don't know when the previous server player's client's tablist entry has been removed. (`ServerPostConnectEvent` and `ServerConnectedEvent` occur before the player receives the "player left the game" message from the server) If I modify the tablist at this point, the entry will be deleted later. So, players who switch servers can see players from all other servers, but players from the previous server can't see this player
2. Currently, when a player's permission is changed, the player's available command list will not be updated immediately, but will only be updated when the server sends the next command suggestion list (such as player gain/lose op, switch server, login again)
3. If I want to use a custom chat message format, I need to intercept the message in `PlayerChatEvent` and reformat the message and then proxy it to all players. But when I use [MCDR](https://github.com/Fallen-Breath/MCDReforged) on the server, because the chat messages are not sent directly to the server, this will make the command system of MCDR unavailable (because the command system of MCDR is realized by directly parsing the chat messages of the console). So I want to achieve this function by intercepting the message sent by the server to the client instead of intercepting the message sent by the client to the server

**Comment by Xernium** [comment]
1. This happens because the connection with the last server is only terminated around the same time the ServerPostConnect Event for the new server is finished. With the conclusion of the ServerConnectedEvent the new connection can no longer be aborted and the player will disconnect from the old server. 
2. That is intentional. Velocity doesn’t store the server command tree so it can’t update suggestions directly. This may be revisited in the future.
3. Velocity will have a custom chat message formatting api going forward to allow interaction with 1.19 and newer in the near future. Intercepting the messages sent by a server is outside the scope of Velocity. That may also change in the future if it can be done without any performance impact during normal operation.
4. That’s outside the scope of Velocity. If that mod uses plugin messaging you can implement that and update it with a proxy plugin

**Comment by Sanluli36li** [comment]
For the first case, is there any event now to know that the player was actually deleted by the previous server?
