### ISSUE TITLE
rcon support

### ISSUE THREAD

**Issue by skyfsj** [PaperMC/Velocity#833]
Can you add rcon support?

**Comment by 4drian3d** [comment]
> Can you add rcon support?

I don't think it is necessary to add rcon support, currently you can use a plugin like https://github.com/UnioDex/VelocityRcon

**Comment by BBaoVanC** [comment]
> > Can you add rcon support?
> 
> I don't think it is necessary to add rcon support, currently you can use a plugin like https://github.com/UnioDex/VelocityRcon

fun fact, this is what [`itzg/docker-bungeecord`](https://github.com/itzg/docker-bungeecord) uses when you set `ENABLE_RCON`

**Comment by half-nothing** [comment]
> > > Can you add rcon support?
> > 
> > 
> > I don't think it is necessary to add rcon support, currently you can use a plugin like https://github.com/UnioDex/VelocityRcon
> 
> fun fact, this is what [`itzg/docker-bungeecord`](https://github.com/itzg/docker-bungeecord) uses when you set `ENABLE_RCON`

Really?I don't know it until today,That's really inconceivable.
Actually I have already tried [VelocityRcon](https://github.com/UnioDex/VelocityRcon) in May this year.But it has some problems and this is the [issue](https://github.com/UnioDex/VelocityRcon/issues/6) which I opened on 7 May.I don't know whether it has been solved or not.So I'd like to have bulid-in rcon support too.

**Comment by electronicboy** [comment]
The issue in that report is unfixable without explicitly adding API for plugins to "close" (or, well, finalise) a command execution, velocity is not designed in a way which is forgiving to how rcon actually works

**Comment by half-nothing** [comment]
> The issue in that report is unfixable without explicitly adding API for plugins to "close" (or, well, finalise) a command execution, velocity is not designed in a way which is forgiving to how rcon actually works

That is to say, the plugin is unable to know where the command execution ends?
So now the best way to solve all the problem is let the author to add rcon support?But if velocity was never intended to be rcon compatible.It will be impossible because it means change the underlying architecture of velocity.I'm not very professional so this is simply my personal guess.

**Comment by electronicboy** [comment]
rcon is transactional, that means that, you send a command (and an id), it sends you a response to that command with that id; 
what rcon servers do, is
await request > dispatch to executor > command executes > command fin > send reply

reply being the messages from plugins all batched up

issue is that when you get to some plugins, i.e. LuckPerms, they do their own processing async, so what you get is
await request > dispatch to executor > command executes *and submits task async* > command fin > send reply
*subitted task runs after send reply* > sends message to rcon queue

but, the response has already been sent, so that message just sits in the queue; if you was to send another command later, I bet that you'd probably get the response for the previous command

**Comment by half-nothing** [comment]
> rcon is transactional, that means that, you send a command (and an id), it sends you a response to that command with that id; what rcon servers do, is await request > dispatch to executor > command executes > command fin > send reply
> 
> reply being the messages from plugins all batched up
> 
> issue is that when you get to some plugins, i.e. LuckPerms, they do their own processing async, so what you get is await request > dispatch to executor > command executes _and submits task async_ > command fin > send reply _subitted task runs after send reply_ > sends message to rcon queue
> 
> but, the response has already been sent, so that message just sits in the queue; if you was to send another command later, I bet that you'd probably get the response for the previous command

In other words, the command returns the result before it has finished executing?
Actually,the problem is exist.I must run the command twice to get the result.

**Comment by electronicboy** [comment]
Yes, which means that the response isn't captured by the rcon server, as the response comes later; You'd specifically need to add API to allow a plugin to delay the rcon response

**Comment by half-nothing** [comment]
Anyway,thanks to your explaination.
Maybe I need to modify the plugin to add some delay.
