### ISSUE TITLE
/server command can not be used in other plugin

### ISSUE THREAD

**Issue by YKDZ** [PaperMC/Velocity#848]
I want to use /server command in some plugin like DeluxeHub or Citizens 2 that could let player select server without command. 
But when I try to do this, the console just told me that this is an Unknown command.
It seems that only player can execute this command.

**Comment by electronicboy** [comment]
Because the command doesn't exist on the servers, it exists on the proxies; and the proxy relies on the fact that it's acting as a proxy to intercept commands defined by velocity; For the actual backend servers, you need plugins which will use the bungee messaging channel to do the server switching, not trying to use the proxy commands on the backend servers
