### ISSUE TITLE
add commands /alert /find /send and maybe /hub

### ISSUE THREAD

**Issue by ghost** [PaperMC/Velocity#862]
add commands /alert /find /send and maybe /hub

**Comment by kyngs** [comment]
I don't think this is a good idea, because there are already plugins to do this. IMO even /server should be removed.

EDIT: To further explain my statement, I think that these commands are not suitable for more extensive networks for the following reasons:
/send, /server - Permission issues, one cannot restrict to which servers a player can be let in.
/alert - Chat formatting issues
/hub - How would Velocity choose the server a player needs to be connected to if there's more than one hub? Shouldn't this just be an alias to /server hub?
/find - Permission issues. What if a head admin is on some super secret server and a trial moderator exposes it? [See this for a brilliant (similar) example.](https://hypixel-skyblock.fandom.com/wiki/SkyBlock_Prototype#Background)

Finally, I realize that most of these issues could be resolved, however it would be unnecessarily complicated and useless, considering that there are plugins for it. See VTools https://github.com/strifel/VTools

**Comment by AVuTuVA** [comment]
https://github.com/Elytrium/VelocityTools/releases/download/dev-build/velocity_tools-1.1.8-SNAPSHOT.jar
