### ISSUE TITLE
1.19.2: out-of-order chat

### ISSUE THREAD

**Issue by BearLeonLight** [PaperMC/Velocity#876]
I keep getting kicked after chatting, I'm not sure if it's a plugin or a server issue.

I'm on another server using the same version of the purpur plugin as up to date.

I don't have this problem on Bungee.

https://gist.github.com/BearLeonLight/cc4a9b3a0b182da14c98563e9131b7db

**Comment by AVuTuVA** [comment]
Pufferfish.yml 
disable-out-of-order-chat: true

**Comment by Xernium** [comment]
Cannot reproduce. Remove any of the paid plugins and try without them. We may be able to help, but not as long as those are involved.

**Comment by BearLeonLight** [comment]
> Cannot reproduce. Remove any of the paid plugins and try without them. We may be able to help, but not as long as those are involved.

it works fine after I re-adjust the proxy settings.
 
`force-key-authentication=false -> true `
Cooperate with NoEncryption-1.19.2-3.1 to complete the function of closing chat report.
kangarko/ChatControl-Red#2132

**Comment by Xernium** [comment]
That one thing has absolutely nothing to do with the other. Also you should keep in mind that using this plugin will break the server in the near future if you’re using Velocity. 
But at the end of the day this issue is neither a Paper nor Velocity issue.
Please open a new issue if you have the same problem with a plugin that allows us to reproduce the issue. Otherwise we can’t help.
