### ISSUE TITLE
Players' IP addresses are logged only when disconnected.

### ISSUE THREAD

**Issue by DoreK333** [PaperMC/Velocity#886]
When a player joins Velocity, only his nickname is visible in the logs. In order for his IP address to be logged, he must disconnect.

I believe that the player's IP address should also be logged when joining Velocity.

This is troublesome in the case of applications such as fail2ban, which take appropriate action based on the logs.

**Comment by Xernium** [comment]
Velocity is designed to not log this as a part of the DoS hardening that is intrinsic to the connection handler. While I agree it may be useful to add the IP after a successful login, anything before it is only to the detriment of normal users. 
Regardless, it is possible for plugins to implement this functionality so I don‘t see a compelling reason to change the very intentional design on this side
