### ISSUE TITLE
Declined resource pack status not sent when connecting to another server

### ISSUE THREAD

**Issue by SamB440** [PaperMC/Velocity#933]
I have a plugin installed on two backend servers that manage resource packs. It sends a resource pack to the player when they join. This works fine if you join one of these servers directly.

You can connect to server 1 and server 2 directly via a forced host. Let's say, in our server list, we have server 1 set to decline any resource pack requests on our client. We will join server 1. Server 1 receives the status that we have declined the resource pack, as expected.

However, if we now switch to server 2 using `/server server-2`, server 2 never receives the declined status from our client.

The resourcepack is 100% sent to the client in both instances and I have tested with a client mod that it does indeed receive the resource pack on both servers.

With a plugin on the proxy, I have confirmed that it does receive the response from the client, it is simply not forwarded to the backend server. I've also tried delaying the sending by several seconds, the same problem happens.

Accepted resource pack statuses work as expected, this only happens with declined. In both cases the resource pack is not set to required.

**Comment by Xernium** [comment]
The state machine is a bit iffy here, if you declined the resource pack on the client then Velocity should automatically respond to all requests itself with a “denied” response unless they’re forced- Since forwarding them would be redundant, this is what *should* happen. 
https://github.com/PaperMC/Velocity/blob/8a048f0505b0034e848b2995192f1dd4695b0857/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java#L1026 this happens here, though I am not sure where the issue may be

**Comment by 4drian3d** [comment]
Fixed in https://github.com/PaperMC/Velocity/pull/1234
