### ISSUE TITLE
1.19.3 Kicked for spamming issue

### ISSUE THREAD

**Issue by JoelSoep** [PaperMC/Velocity#944]
Stacktrace: https://pastebin.com/VsBG0aEH

This happens when a player gets kicked for spamming on a 1.19.3 server.
Velocity doesn't handle the disconnection right and disconnects the player from the proxy with the message "An internal error occurred in your connection."

I am using Velocity version 3.2.0 (Snapshot version 255) & Paper 1.19.3 / git-paper-386.

**Comment by Xernium** [comment]
This is very intentional. The client sent another command/chat packet while the server connection was already closed and the proxy was in the process of figuring out what to do next. This can only ever happen if mods or hacks are in use. This intermittent command/chat packet causes the proxy to immediately disconnect because it is an invalid state. There's no issue here, everything is functioning as intended.

**Comment by Xernium** [comment]
Though I admit the message isn't ideal, that's maybe something we should reconsider
