### ISSUE TITLE
HEX && RGB Support

### ISSUE THREAD

**Issue by ElinCode** [PaperMC/Velocity#976]
messages.properties NOT RGB SUPPORT FIX

**Comment by ElinCode** [comment]
If you can't fix it in messages.properties then make a .yml file

**Comment by Xernium** [comment]
This is known, the message property file will support the MiniMessage format in the future but not the problematic Bungeecord hex color format

**Comment by 4drian3d** [comment]
> If you can't fix it in messages.properties then make a .yml file

I was working on it in the pull requests https://github.com/PaperMC/Velocity/pull/721 and https://github.com/PaperMC/Velocity/pull/718 . But yesterday Adventure released its version 4.13.0 that implements https://github.com/KyoriPowered/adventure/pull/871 but in order to use it in Velocity,  it is necessary to create an own TranslationRegistry system or implement support for a "postprocessor" type for the TranslationRegistryImpl of Adventure itself.

And it has nothing to do with the properties format instead of yaml, personally I avoid using yaml as well😅

**Comment by ElinCode** [comment]
А поддержка когда будет приблизительно? Мини Меседж с поддержкой HEX?

**Comment by ElinCode** [comment]
When will support be available? Mini Message with HEX support?

**Comment by electronicboy** [comment]
There is no eta, in the meantime, you can use a plugin, like minimotd

**Comment by 4drian3d** [comment]
> There is no eta, in the meantime, you can use a plugin, like minimotd

This issue is about MiniMessage support in Velocity translations.
For the motd issue, yesterday PaperMC/Velocity#666 was merged which adds MiniMessage support to the motd configuration option

**Comment by 4drian3d** [comment]
Also, this issue is duplicate of #720

**Comment by electronicboy** [comment]
oh, derp;

Well, duplicate of #720

**Comment by ElinCode** [comment]
> Also, this issue is duplicate of #720


I don't need HEX in the mod, but in messages.properties

**Comment by 4drian3d** [comment]
> > Also, this issue is duplicate of #720
> 
> I don't need HEX in the mod, but in messages.properties

That is why this issue is duplicated

**Comment by BrIruka** [comment]
https://github.com/BrIruka/VelocityHEXMsg
